### ISSUE TITLE
Example code forgot a "\n"

### ISSUE THREAD

**Issue by schloerke** [hadley/helpr#1]
when performing "?old.packages" helpr errors saying:

ERROR: 
/var/folders/Ke/KelkGmsJE-eNQMXzYVwckk+++TI/-Tmp-//RtmpPSz4hx/file7c9e57b:3:50
    unexpected ','

1: do.call(function (package, topic) 
   {
       topic_info <- parse_help(pkg_topic(package, topic))
       topic_info$package <- package
       render_brew("topic", topic_info, path = path)
   }, structure(list(package = "utils", topic = "update.packages"), .Names = c("package", 
   "topic")))
2: function (package, topic) 
   {
       topic_info <- parse_help(pkg_topic(package, topic))
       topic_info$package <- package
       render_brew("topic", topic_info, path = path)
   }(package = "utils", topic = "update.packages")
3: parse_help(pkg_topic(package, topic))
4: highlight(reconstruct(untag(rd$examples)))
5: parser(text = examples)

The file location changes, as it is only a temp file.

The example code is missing a return statement:
    ## Not runinstall.packages(
        c("XML_0.99-5.tar.gz",
          "../../Interfaces/Perl/RSPerl_0.8-0.tar.gz"),
        repos = NULL,
        configure.args = c(XML = '--with-xml-config=xml-config',
                           RSPerl = "--with-modules='IO Fcntl'"))##

But I don't know how to fix it.

**Comment by hadley** [comment]
Fixed in 91af07d3371431266b12b3184728e0e2bdf26e50
