### ISSUE TITLE
'ex-parser' not found while running reconstruct()

### ISSUE THREAD

**Issue by ddpyle** [hadley/helpr#10]
In using reconstruct(), when I execute the following code using commit hadley-helpr-e1b3562, everything works. But with commit hadley-helpr-1edbfa1, I receive the following error once for each "unique topic" in the target package:

"Error in attr(ex_parser, "data") <- d : object 'ex_parser' not found".

R code:

library(mutatr)
library(brew)
library(stringr)
library(testthat)
library(highlight)
library(helpr)

unique.topics <- function(package) { 
  all_topics <- pkg_topics_index(package)
  unique_topics <- unique(all_topics$file)

  unique_topics
}

text <- function(top) {
  pkg.text <- reconstruct(unlist(top))
  pkg.text <- str_c(pkg.text, sep = " ", collapse = " ")
}

document <- function(package) {
unique_topics <- unique.topics(package)
document <- llply(llply(unique_topics, failwith(NULL, top)), text)
}

package <- "stats"
unique.topics(package)

top <- function(unique_topics) {
  topics <- topic("stats", unique_topics)
}

doc.stats <- document(package)
# End

**Comment by schloerke** [comment]
fixed it.  sorry.  Silly mistake.
