### ISSUE TITLE
Package Description needs to be reconstructed

### ISSUE THREAD

**Issue by schloerke** [hadley/helpr#12]
The package description needs to be reconstructed.

YaleToolkit has "\code" inside of the package description.  The bad part is that it doesn't have any tags.

**Comment by hadley** [comment]
I think package descriptions are supposed to be plain text.

**Comment by schloerke** [comment]
Writing R Extensions
...
The DESCRIPTION file should be written entirely in ASCII for maximal portability.
...

It should be in ASCII, not Latex.
