### ISSUE TITLE
?package_name

### ISSUE THREAD

**Issue by schloerke** [hadley/helpr#3]
So when ?brew is executed.  It goes to:
http://127.0.0.1:11418/packages/brew/topics/brew

When it should go to the package page instead.  BUT 
a <- ?brew
a[1]

shows that it exists, but there is no file there.

**Comment by hadley** [comment]
`package?brew` is the way you normally get to a package help page (if it exists).  Are you sure that link isn't for the brew function in the brew package?

**Comment by schloerke** [comment]
But then when I do
    ?brew
it takes me to :
    http://127.0.0.1:15871/packages/brew/topics/brew
which says the file doesn't exist.

**Comment by schloerke** [comment]
So how would we like to handle when people do:
    ?brew:::brew
It gives the site:
    /package/brew/topic/brew
but it is for an internal function that isn't showing up in the brew package page

**Comment by hadley** [comment]
brew::brew isn't an internal function.  `help(package = brew)` lists it

**Comment by schloerke** [comment]
fixed it.

7f56e9da43f5af3cdb1afc8f2db6970e55766d53

The pkg_topics_index was removing the first row by putting it into the header and replacing that with "alias" and "file".

So, "brew" was being covered up.
