### ISSUE TITLE
Weird md5 warning message

### ISSUE THREAD

**Issue by schloerke** [hadley/helpr#4]
I get this message
    Warning message:
    In structure(.Call(Rmd5, files), names = files) :
      md5 failed on file '/Users/barret/Dropbox/ggobi-svn/helpr/helpr/R/'
    > 

I get it when I load my files at the very beginning.  

I have no clue why it is occurring.  I starting happening after I memoised a function.

**Comment by hadley** [comment]
It's most likely coming from `devtools`.  Can you include a traceback?

**Comment by schloerke** [comment]
```
> l(helpr, reset=TRUE)
Warning message:
In structure(.Call(Rmd5, files), names = files) :
md5 failed on file '/Users/barret/Dropbox/ggobi-svn/helpr/helpr/R/'
> traceback()
No traceback available 
> 
```

**Comment by schloerke** [comment]
It's gone now.  IDK why.
