### ISSUE TITLE
topic() not running for select stat package topics

### ISSUE THREAD

**Issue by ddpyle** [hadley/helpr#9]
The topic() function isn't working with a few of the topics from the stat package. Using the following R code, unique_topics numbers 13, 64, 82, 120, 140 and 141 will not process:

all_topics <- pkg_topics_index("stats")
unique_topics <- unique(all_topics$file)

strip_html <- function(x) {
  str_replace(x, "</?.*?>", "")
}

text <- function(top) {
  str_c(
    strip_html(top$title),
    strip_html(top$details),
    strip_html(top$value),
    strip_html(top$desc), sep = " "
  )
}

n <- length(unique_topics)
documents <- rep(NA, n)

for (i in seq_along(documents)) {
  top <- topic("stats", unique_topics[i])
  documents[i] <- text(top)
}

**Comment by schloerke** [comment]
I have now updated the code to run the above code with no messages and errors.

A lot of them had a \deqn tag and some had text after the arguments were stated, which caused errors.  

http://github.com/hadley/helpr/commit/6d64cde40c157eaca9709c9e26bf62e84678e50c
